tests/adt-run: Fix test regression when $ADT_TEST* are not set
While the tests are being skipped, __init__() still runs:

  File "/tmp/adt-run.E0LPjX/build.Ktm/autopkgtest-3.17.1/tests/adt-run", line 2858, in __init__
    super(QemuRunner, self).__init__(['qemu', os.environ['ADT_TEST_QEMU']], *args, **kwargs)
  File "/usr/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'ADT_TEST_QEMU'